# Generated by Django 5.2.7 on 2025-10-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_company', '0002_companyprofile_company_description_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='annual_revenue_eur',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='avoid_keywords',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='certifications_technical',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='competitive_advantages',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='financial_capacity',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='geographic_presence',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='main_competitors',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='max_concurrent_bids',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='overcommitment_risk',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='preferred_contract_types',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='preferred_regions',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='previous_clients',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='programming_languages',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='public_sector_experience',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='relevant_projects',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='size',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='team_availability',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='technical_areas',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='technologies',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='weaknesses',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='years_in_business',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='preferred_nuts_regions',
            field=models.JSONField(blank=True, default=list, help_text='Ej: ES30 (Madrid), ES51 (Barcelona)', verbose_name='Regiones de interés (NUTS)'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='budget_range',
            field=models.JSONField(blank=True, default=dict, help_text='{"min": 50000, "max": 500000}', verbose_name='Rango de presupuesto'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_description_text',
            field=models.TextField(blank=True, help_text='Describe tu empresa: qué hacéis, en qué sectores trabajáis, ubicación, etc. Esta información ayudará a encontrar las licitaciones más relevantes.', verbose_name='Cuéntanos sobre tu empresa'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(max_length=200, verbose_name='Nombre de la empresa'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='employees',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de empleados'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='preferred_cpv_codes',
            field=models.JSONField(blank=True, default=list, help_text='Códigos CPV relacionados con tu actividad', verbose_name='Códigos CPV de interés'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='sectors',
            field=models.JSONField(blank=True, default=list, help_text='Ej: Tecnología, Construcción, Consultoría', verbose_name='Sectores'),
        ),
    ]
