# Generated by Django 5.0.14 on 2025-11-22 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps_company", "0003_remove_companyprofile_annual_revenue_eur_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Nombre completo"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Alicante, Madrid, Barcelona",
                        max_length=100,
                        verbose_name="Ciudad/Provincia",
                    ),
                ),
                (
                    "curriculum_text",
                    models.TextField(
                        blank=True,
                        help_text="Pega aquí tu CV o descríbete profesionalmente. La IA analizará esta información.",
                        verbose_name="Curriculum en texto",
                    ),
                ),
                (
                    "curriculum_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="curriculos/",
                        verbose_name="CV en PDF",
                    ),
                ),
                (
                    "skills",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Habilidades técnicas y blandas extraídas del CV",
                        verbose_name="Habilidades",
                    ),
                ),
                (
                    "experience",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"company": "", "position": "", "duration": "", "description": ""}]',
                        verbose_name="Experiencia laboral",
                    ),
                ),
                (
                    "education",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"institution": "", "degree": "", "year": ""}]',
                        verbose_name="Formación",
                    ),
                ),
                (
                    "languages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"language": "", "level": ""}]',
                        verbose_name="Idiomas",
                    ),
                ),
                (
                    "professional_summary",
                    models.TextField(
                        blank=True,
                        help_text="Resumen generado por IA basado en el CV",
                        verbose_name="Resumen profesional",
                    ),
                ),
                (
                    "preferred_locations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Ej: ["Alicante", "Valencia", "Remoto"]',
                        verbose_name="Ubicaciones preferidas",
                    ),
                ),
                (
                    "preferred_sectors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Ej: ["Informática/IT", "Marketing"]',
                        verbose_name="Sectores de interés",
                    ),
                ),
                (
                    "job_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Ej: ["Remoto", "Presencial", "Híbrido"]',
                        verbose_name="Tipos de trabajo",
                    ),
                ),
                (
                    "contract_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Ej: ["Indefinido", "Temporal", "Freelance"]',
                        verbose_name="Tipos de contrato",
                    ),
                ),
                (
                    "salary_min",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Salario mínimo (€/año)"
                    ),
                ),
                (
                    "salary_max",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Salario máximo (€/año)"
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Inmediata, 15 días, 1 mes",
                        max_length=50,
                        verbose_name="Disponibilidad",
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, verbose_name="Perfil de LinkedIn"),
                ),
                (
                    "github_url",
                    models.URLField(blank=True, verbose_name="Perfil de GitHub"),
                ),
                (
                    "portfolio_url",
                    models.URLField(blank=True, verbose_name="Portfolio/Web personal"),
                ),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "cv_analyzed",
                    models.BooleanField(
                        default=False, verbose_name="CV analizado por IA"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuarios",
            },
        ),
        migrations.DeleteModel(
            name="CompanyProfile",
        ),
    ]
