# Generated by Django 5.1.6 on 2025-11-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_company', '0004_userprofile_delete_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cv_image',
            field=models.ImageField(blank=True, help_text='Sube una imagen de tu CV para análisis con IA Vision', null=True, upload_to='cv_images/', verbose_name='CV en imagen'),
        ),
    ]
