# Generated by Django 5.1.6 on 2025-11-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_company', '0005_userprofile_cv_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cv_summary',
            field=models.JSONField(blank=True, default=dict, help_text='Resumen optimizado para búsqueda de empleo', verbose_name='Resumen CV estructurado'),
        ),
    ]
