# Generated by Django 5.1.6 on 2025-11-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_company', '0006_add_cv_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cv_summary',
            field=models.TextField(blank=True, help_text='Resumen optimizado para búsqueda de empleo', verbose_name='Resumen CV estructurado'),
        ),
    ]
