# Generated by Django 5.1.6 on 2025-10-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="company_description_text",
            field=models.TextField(
                blank=True,
                help_text="Descripción libre de tu empresa. La IA extraerá información clave automáticamente.",
            ),
        ),
    ]
