# Generated by Django 5.2.6 on 2025-10-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps_tenders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="parsed_summary",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Campos parseados del XML: REQUIRED, OPTIONAL, META",
                verbose_name="Resumen estructurado del XML",
            ),
        ),
    ]
