# Generated by Django 5.2.7 on 2025-11-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_tenders', '0002_tender_parsed_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='contact_fax',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fax de contacto'),
        ),
    ]
