# Generated by Django 5.1.6 on 2025-11-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_authentication', '0011_add_browse_chunk_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_mode',
            field=models.CharField(blank=True, choices=[('any', 'Indiferente'), ('remote', 'Remoto'), ('onsite', 'Presencial'), ('hybrid', 'Híbrido')], default='any', help_text='Tu preferencia de modalidad de trabajo', max_length=20, verbose_name='Modalidad de trabajo'),
        ),
    ]
